# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: /home/delorenj/.local/share/mise/installs/node/26.5.0/lib/node_modules/@delorenj/pjangler/templates/commonproject
project_description: 
project_name: Ssbnk
ticket_provider: plane
